name: flutter_devcamp_firebase
description: "Flutter Firebase authentication"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: 2.4.13
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: 5.4.4
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: 1.0.8
  # https://pub.dev/packages/dio
  dio: 5.7.0
  # https://pub.dev/packages/go_router
  go_router: 14.3.0
  # https://pub.dev/packages/firebase_core
  firebase_core: 3.6.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: 5.3.1
  # https://pub.dev/packages/flutter_hooks
  flutter_hooks: 0.20.5
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: 2.5.3
  # https://pub.dev/packages/hooks_riverpod
  hooks_riverpod: 2.5.4
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: 2.5.3
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: 4.0.0
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: 2.4.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
